# Generated by Django 5.2.4 on 2025-07-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('input_constraints', models.TextField()),
                ('output_format', models.TextField()),
                ('sample_input_1', models.TextField()),
                ('sample_output_1', models.TextField()),
                ('sample_input_2', models.TextField(blank=True, null=True)),
                ('sample_output_2', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
