# Generated by Django 5.2.4 on 2025-07-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='memory_limit',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='time_limit',
            field=models.FloatField(default=1.0),
        ),
    ]
