# Generated by Django 5.2.4 on 2025-07-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_codingproblem_difficulty_codingproblem_memory_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingproblem',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='memory_limit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='tags',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codingproblem',
            name='time_limit',
            field=models.CharField(max_length=50),
        ),
    ]
