# Generated by Django 5.2.4 on 2025-08-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_solvedproblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingproblem',
            name='description',
        ),
    ]
