# Generated by Django 5.2.4 on 2025-08-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_codingproblem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingproblem',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
