# Generated by Django 5.2.4 on 2025-08-06 20:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_codingproblem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingproblem',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
