# Generated by Django 5.2.4 on 2025-07-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
        ('home', '0004_testcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesubmission',
            old_name='timestamp',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.codingproblem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codesubmission',
            name='verdict',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='language',
            field=models.CharField(max_length=10),
        ),
    ]
